# Generated by Django 4.2.30 on 2026-05-29 06:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Caracteristica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(verbose_name='Número de la Característica')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Factor',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField(unique=True, verbose_name='Número del Factor')),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Indicador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.CharField(max_length=10, verbose_name='Número del Indicador (Ej: 1.1)')),
                ('descripcion', models.TextField()),
                ('caracteristica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='indicadores', to='evaluacion.caracteristica')),
            ],
        ),
        migrations.CreateModel(
            name='Pregunta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('enunciado', models.TextField(verbose_name='Enunciado de la Pregunta')),
                ('estamento_dirigido', models.CharField(choices=[('Estudiantes', 'Estudiantes'), ('Docentes', 'Docentes'), ('Egresados', 'Egresados'), ('Administrativos', 'Administrativos'), ('Directivos', 'Directivos'), ('Empleadores', 'Empleadores'), ('Todos', 'Todos')], max_length=50)),
                ('indicador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preguntas', to='evaluacion.indicador')),
            ],
        ),
        migrations.AddField(
            model_name='caracteristica',
            name='factor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='caracteristicas', to='evaluacion.factor'),
        ),
    ]
