# Generated by Django 4.2.30 on 2026-05-30 03:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('evaluacion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Respuesta',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('valoracion', models.IntegerField(choices=[(5, 'Totalmente de acuerdo'), (4, 'De acuerdo'), (3, 'Ni de acuerdo ni en desacuerdo'), (2, 'En desacuerdo'), (1, 'Totalmente en desacuerdo'), (0, 'No Sabe / No Aplica')], verbose_name='Valoración Likert')),
                ('estamento', models.CharField(max_length=50)),
                ('fecha_registro', models.DateTimeField(auto_now_add=True)),
                ('pregunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respuestas', to='evaluacion.pregunta')),
            ],
        ),
    ]
