# Generated by Django 4.2.30 on 2026-05-18 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Superusuario',
            fields=[
                ('dni', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=255)),
                ('universidad', models.CharField(default='Universidad de Nariño', max_length=255)),
                ('programa', models.CharField(default='Ingeniería en Producción Acuícola', max_length=255)),
                ('id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=255)),
                ('universidad', models.CharField(default='Universidad de Nariño', max_length=255)),
                ('programa', models.CharField(default='Ingeniería en Producción Acuícola', max_length=255)),
                ('semestre', models.CharField(max_length=50)),
                ('tipo', models.CharField(max_length=50)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.superusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Empleador',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=255)),
                ('rol', models.CharField(max_length=100)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.superusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Egresado',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=255)),
                ('universidad', models.CharField(default='Universidad de Nariño', max_length=255)),
                ('programa', models.CharField(default='Ingeniería en Producción Acuícola', max_length=255)),
                ('tipo', models.CharField(max_length=50)),
                ('rol', models.CharField(max_length=100)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.superusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=255)),
                ('universidad', models.CharField(default='Universidad de Nariño', max_length=255)),
                ('programa', models.CharField(default='Ingeniería en Producción Acuícola', max_length=255)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.superusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Directivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=255)),
                ('universidad', models.CharField(default='Universidad de Nariño', max_length=255)),
                ('programa', models.CharField(default='Ingeniería en Producción Acuícola', max_length=255)),
                ('rol', models.CharField(max_length=100)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.superusuario')),
            ],
        ),
        migrations.CreateModel(
            name='Administrativo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=10)),
                ('correo', models.CharField(max_length=255)),
                ('universidad', models.CharField(default='Universidad de Nariño', max_length=255)),
                ('programa', models.CharField(default='Ingeniería en Producción Acuícola', max_length=255)),
                ('rol', models.CharField(max_length=100)),
                ('dni', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='usuarios.superusuario')),
            ],
        ),
    ]
