# Generated by Django 4.2.30 on 2026-05-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_alter_estudiante_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='estudiante',
            name='dni',
            field=models.CharField(max_length=20, unique=True, verbose_name='Documento de Identidad'),
        ),
    ]
