# Generated by Django 4.2.30 on 2026-05-26 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_alter_docente_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='egresado',
            name='dni',
            field=models.CharField(max_length=20, unique=True, verbose_name='Documento de Identidad'),
        ),
    ]
