# Generated by Django 4.2.30 on 2026-05-26 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_alter_egresado_dni'),
    ]

    operations = [
        migrations.AddField(
            model_name='egresado',
            name='empresa',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
