# Generated by Django 4.2.30 on 2026-05-26 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0006_egresado_empresa'),
    ]

    operations = [
        migrations.RenameField(
            model_name='administrativo',
            old_name='rol',
            new_name='cargo',
        ),
        migrations.RenameField(
            model_name='directivo',
            old_name='rol',
            new_name='cargo',
        ),
        migrations.RemoveField(
            model_name='empleador',
            name='rol',
        ),
        migrations.AddField(
            model_name='empleador',
            name='empresa',
            field=models.CharField(default='Sin empresa', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='administrativo',
            name='dni',
            field=models.CharField(max_length=20, unique=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='directivo',
            name='dni',
            field=models.CharField(max_length=20, unique=True, verbose_name='Documento'),
        ),
        migrations.AlterField(
            model_name='empleador',
            name='dni',
            field=models.CharField(max_length=20, unique=True, verbose_name='Documento'),
        ),
    ]
